from __future__ import annotations

import argparse
import json
from pathlib import Path

from slideshow_maker.copywriter import STYLES, resolve_style
from slideshow_maker.errors import SlideshowError
from slideshow_maker.formats import get_format
from slideshow_maker.models import RunConfig
from slideshow_maker.pipeline import GenerationPipeline, validate_format_definition


def main() -> None:
    parser = argparse.ArgumentParser(prog="slideshow-maker")
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Generate slideshow variations")
    gen.add_argument("--format", required=True, dest="format_id")
    gen.add_argument("--count", required=True, type=int)
    gen.add_argument("--input", required=True, dest="input_dir")
    gen.add_argument("--out", required=True, dest="out_dir")
    gen.add_argument("--seed", type=int, default=None)
    gen.add_argument(
        "--source-mode",
        choices=["local", "local+flow", "flow"],
        default="local",
        help="Image sourcing mode",
    )
    gen.add_argument(
        "--copy-review",
        dest="copy_review",
        default=None,
        help="Path to reviewed copy JSON generated by draft-copy",
    )
    gen.add_argument(
        "--copy-style",
        choices=sorted(STYLES),
        default="balanced",
        help="TikTok copy tone preset",
    )

    draft = sub.add_parser("draft-copy", help="Generate draft copy JSON for review before rendering")
    draft.add_argument("--format", required=True, dest="format_id")
    draft.add_argument("--count", required=True, type=int)
    draft.add_argument("--input", required=True, dest="input_dir")
    draft.add_argument("--out", required=True, dest="out_dir")
    draft.add_argument("--seed", type=int, default=None)
    draft.add_argument(
        "--copy-out",
        dest="copy_out",
        default=None,
        help="Optional explicit path for temp copy JSON",
    )
    draft.add_argument(
        "--copy-style",
        choices=sorted(STYLES),
        default="balanced",
        help="TikTok copy tone preset",
    )

    val = sub.add_parser("validate-format", help="Validate a format definition")
    val.add_argument("--format", required=True, dest="format_id")

    prev = sub.add_parser("preview", help="Preview a generated plan with mock assets")
    prev.add_argument("--format", required=True, dest="format_id")
    prev.add_argument("--variation-seed", required=True, type=int)

    args = parser.parse_args()

    try:
        fmt = get_format(args.format_id)

        if args.command == "validate-format":
            info = validate_format_definition(fmt)
            print(json.dumps(info, indent=2))
            return

        pipeline = GenerationPipeline(fmt)

        if args.command == "preview":
            preview = pipeline.preview(seed=args.variation_seed)
            print(json.dumps(preview, indent=2, default=str))
            return

        if args.command in {"generate", "draft-copy"} and args.count <= 0:
            raise SlideshowError("--count must be a positive integer")

        config = RunConfig(
            format_id=args.format_id,
            count=getattr(args, "count", 1),
            input_dir=Path(getattr(args, "input_dir", ".")).expanduser().resolve(),
            out_dir=Path(getattr(args, "out_dir", ".")).expanduser().resolve(),
            seed=getattr(args, "seed", None),
            source_mode=getattr(args, "source_mode", "local"),
            copy_review_path=Path(args.copy_review).expanduser().resolve() if getattr(args, "copy_review", None) else None,
            copy_style=resolve_style(getattr(args, "copy_style", "balanced")),
        )

        if args.command == "draft-copy":
            copy_out = Path(args.copy_out).expanduser().resolve() if args.copy_out else None
            result = pipeline.draft_copy(config, draft_path=copy_out)
            print(json.dumps(result, indent=2, default=str))
            return

        if args.command == "generate":
            summaries = pipeline.generate(config)
            print(json.dumps({"generated": summaries}, indent=2))
            return

    except SlideshowError as exc:
        raise SystemExit(f"Error: {exc}") from exc
    except ValueError as exc:
        raise SystemExit(f"Error: {exc}") from exc


if __name__ == "__main__":
    main()
